/**
 * Footer — small bottom bar.
 */
export default function Footer() {
  return (
    <footer className="border-t border-white/10 mt-12 py-6 text-center text-slate-500 text-xs">
      Office-IoT · Local-only demo build · Data is generated by an in-process simulator.
    </footer>
  );
}